url: "https://hato1198.github.io"
baseurl: "/mouse-cursor-checker"

title: "マウスカーソル確認ツール"
description: "13種類のマウスカーソルの見た目をWEB上で簡単にチェックできるサイトです。設定変更の確認に便利な無料ツールです。"
author: "hato1198"

plugins:
  - jekyll-sitemap

exclude:
  - google7aa94270c7800c73.html

sitemap:
  hostname: "https://hato1198.github.io"

timezone: "Asia/Tokyo"
