url: "https://hato1198.github.io"
baseurl: "/mouse-cursor-checker"

title: "マウスカーソル確認ツール"
description: "マウスカーソルの見た目をチェックできるシンプルなサイトです。"
author: "hato1198"

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - google7aa94270c7800c73.html

sitemap:
  hostname: "https://hato1198.github.io/mouse-cursor-checker"

timezone: "Asia/Tokyo"
