url: "https://hato1198.github.io"
baseurl: "mouse-cursor-checker/"

title: "マウスカーソル確認ツール"
description: "13種類のマウスカーソルの見た目をWEB上で簡単にチェックできるサイト。設定変更の確認に便利な無料ツールです。"
author: "hato1198"

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

sitemap:
  hostname: "https://hato1198.github.io/mouse-cursor-checker/"

timezone: "Asia/Tokyo"
